member/urls.py
from django.conf.urls import url
from . import views

from .forms import MemberForm
from django import forms

app_name = 'member'
urlpatterns = [

    url(r'^$', views.HomePageView.as_view(), name='home'),

    # Member
    url(r'^(?P<pk>[0-9]+)/$', views.MemberDetailView.as_view(), name='member-detail'),
    url(r'member/add/$', views.AlbumCreate.as_view(), name='member-add'),
    url(r'^person/$', views.GeneralMemberView.as_view(), name='person-list'),
    url(r'^lifemember/$', views.LifeMemberView.as_view(), name='lifemember-list'),
    url(r'^person/create$', views.PersonCreate.as_view(), name='person-create'),
    url(r'^person/(?P<pk>[0-9]+)/update$', views.PersonUpdate.as_view(), name='person-update'),
    url(r'^person/(?P<pk>[0-9]+)/delete$', views.PersonDelete.as_view(), name='person-delete'),
    url(r'^allmember/$', views.AllMemberListView.as_view(), name='all-member'),

    # Executive Member
    url(r'^execomember/$', views.ExeCommListView.as_view(), name='execomember-list'),
    url(r'^execomember/create$', views.ExeCommMembCreate.as_view(), name='execomember-create'),

    # Member Category
    url(r'^membercat/$', views.MembershipView.as_view(), name='member-cat'),
    url(r'^membercat/create/$', views.MemberCatCreate.as_view(), name='membercat-create'),

    # Constitution
    url(r'^cons/$', views.ConstitutionView.as_view(), name='cons-list'),
    url(r'^cons/create/$', views.ConstitutionCreate.as_view(), name='cons-create'),
    url(r'^cons/(?P<pk>[0-9]+)/update$', views.ConstitutionUpdate.as_view(), name='cons-update'),
    url(r'^cons/(?P<pk>[0-9]+)/delete$', views.ConstitutionDelete.as_view(), name='cons-delete'),

    # News
    url(r'^news/$', views.NewsListView.as_view(), name='news-list'),
    url(r'^news/create/$', views.NewsCreate.as_view(), name='news-create'),
    url(r'^news/(?P<pk>\d+)/$', views.NewsDetailView.as_view(), name='news-detail'),
    url(r'^news/(?P<pk>[0-9]+)/update/$', views.NewsUpdate.as_view(), name='news-update'),
    url(r'^news/(?P<pk>[0-9]+)/delete/$', views.NewsDelete.as_view(), name='news-delete'),


    # Event and Gallery
    url(r'^gallery/$', views.GalleryList.as_view(), name='gallery-list'),
    url(r'^gallery/(?P<pk>\d+)/$', views.GalleryDetailView.as_view(), name='gallery-detail'),
    url(r'^event/$', views.EventList.as_view(), name='event-list'),
    url(r'^event/(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event-detail'),
    url(r'^event/gallery/$', views.EventGalleryListView.as_view(), name='event-gallery'),
    url(r'^event/create/$', views.EventCreateView.as_view(), name='create_event_and_gallery'),
    url(r'^event/(?P<pk>\d+)/update/$', views.EventUpdateView.as_view(), name='update_event_and_gallery'),
    url(r'^event/(?P<pk>[0-9]+)/delete/$', views.EventDelete.as_view(), name='event-delete'),
    url(r'^gallery/all/$', views.GalleryAllList.as_view(), name='gallery-all'),

    # Search

    url(r'^search/$', views.SearchListView.as_view(), name='search'),
   ]

user/urls.py
from django.conf.urls import include, url
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    RedirectView, TemplateView)

from .views import (
    ActivateAccount, CreateAccount,
    DisableAccount, ProfileDetail, ProfileUpdate,
    PublicProfileDetail, ResendActivationEmail)

password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'user/password_change_form.html',
         'post_change_redirect': reverse_lazy(
            'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'user/password_reset_form.html',
         'email_template_name':
            'user/password_reset_email.txt',
         'subject_template_name':
            'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'user/password_reset_complete.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'user/user_create_done.html')),
        name='create_done'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'^login/$',
        auth_views.login,
        {'template_name': 'user/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name': 'user/logged_out.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='logout'),
    url(r'^password/', include(password_urls)),
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name='profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),
]

member/models.py
from django.db import models
from django.core.urlresolvers import reverse
from .file_validators import file_size, validate_file_extension
from django.conf import settings

from django_resized import ResizedImageField

import datetime
# Create your models here.



class Person(models.Model):
    YEAR_CHOICES = [(r, r) for r in range(1970, datetime.date.today().year + 1)]
    name = models.CharField(max_length=175)
    present_position=models.CharField(max_length=100)
    organization= models.CharField(max_length=150,blank=True)
    address = models.CharField(max_length=250, blank=True)
    tele_land = models.CharField(max_length=15,blank=True)
    tele_cell = models.CharField(max_length=15, blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='member_persons')
    photo= ResizedImageField(size=[70, 70],crop=['middle', 'center'],upload_to='persons/%Y/%m/%d/',null=True,
        blank=True,
        editable=True,
        help_text="Person Picture", validators=[file_size])
    website = models.URLField(blank=True)
    birth_date = models.DateField(null=True,blank=True)
    passing_year = models.IntegerField(('year'), choices=YEAR_CHOICES, default=datetime.datetime.now().year)
    category = models.ForeignKey('Membership', on_delete=models.CASCADE)
    member_since = models.DateField(null=True,blank=True)
    image_height = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")
    image_width = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")
    is_active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('member:member-detail', kwargs={'pk': self.pk})

    def __str__(self):              # __unicode__ on Python 2
        return self.name


    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url

class Membership(models.Model):
    category = models.CharField(max_length=50, blank=False)

    def __str__(self):  # __unicode__ on Python 2
        return self.category


class ExecMember(models.Model):
    name = models.ForeignKey(Person, on_delete=models.CASCADE )
    committee_position = models.CharField(max_length=100)
    rank = models.IntegerField(blank=True)
    member_start_date = models.DateField(blank=True)
    member_end_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering =['rank']

    def __str__(self):  # __unicode__ on Python 2
        return self.committee_position


class Constitution(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now_add=True)
    docfile = models.FileField(upload_to='documents/%Y/%m/%d/',null=True,
        blank=True,
        editable=True,
        help_text="Document File", validators=[file_size])

    def __str__(self):  # __unicode__ on Python 2
        return self.title

class News(models.Model):
    title = models.CharField(max_length=100)
    news = models.TextField()
    docfile = models.FileField(upload_to='news/%Y/%m/%d/', null=True,
                               blank=True,
                               editable=True,
                               help_text="News File",validators=[validate_file_extension, file_size])
    pub_date = models.DateField(auto_now_add=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('member:book-detail', kwargs={'pk': self.pk})

class Event(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField()
    created = models.DateField(auto_now_add=True)

    class Meta:
        ordering =['-created']


    def __str__(self):  # __unicode__ on Python 2
        return self.name

    def get_absolute_url(self):
        return reverse('member:event-detail', kwargs={'pk': self.pk})

class Gallery(models.Model):
    title = models.CharField(max_length=150)
    event = models.ForeignKey(Event, on_delete=models.CASCADE )
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    image = models.ImageField(upload_to='events/%Y/%m/%d/', null=True,
                              blank=True,
                              editable=True,
                              help_text="Event Picture", validators=[file_size], width_field="width", height_field="height")
    pub_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)


    class Meta:
        get_latest_by = 'pub_date'

    def __str__(self):  # __unicode__ on Python 2
        return self.title

    def get_absolute_url(self):
        return reverse('member:gallery-detail', kwargs={'pk': self.pk})

member/templates/member/base_member.html
{% extends parent_template|default:"base.html" %}

member/templates/member/event_and_gallery_form.html
{% extends parent_template|default:"member/base_member.html" %}
{% load crispy_forms_tags %}


{% block title %}{% if form.instance.pk %}Edit{% else %}Add{% endif %} Event and Gallery{% endblock title %}

{% block link %}{{ block.super }}
    <style type="text/css">
    .errorlist {
        list-style: none;
        color: #B94A48;
        margin: 0px 0px 9px 0px;
        padding: 0px;
    }
    </style>
{% endblock link %}

{% block bottom_script %}{{ block.super }}

{% endblock bottom_script %}


{% block body %}

<div class="page-header">
  <h1>{% if form.instance.pk %}Edit{% else %}Add{% endif %} Event and Gallery</h1>
</div>

<div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col-md-8">
                <div class="panel panel-default">
                    <div class="panel-body">

                    <form action="." method="post" enctype="multipart/form-data">
                        {{ formset.management_form }}
                        {% csrf_token %}

                        <legend>Event</legend>
                        <div class="event">
                        {{ form|crispy}}
                        </div>

                        <legend>
                            <div class="pull-right"><a href="#" class="btn btn-inverse add-photo"><i class="icon-plus icon-white"></i> Add Photo</a></div>
                            Photo Gallery
                        </legend>
                        <div class="gallery form-inline">
                            {% for form in formset %}
                                {{ form|crispy }}
                            {% endfor %}
                        </div>
                      <div class="form-actions">
                         <button type="submit" class="btn btn-primary">Save</button>
                       </div>
                     </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

member/templates/member/event_detail.html
{% extends parent_template|default:"member/base_member.html" %}

{% block title %}{{ object.name }}{% endblock title %}

{% block body %}

<div class="page-header">
    <ol class="breadcrumb">
      <li><a href="{% url 'member:event-list' %}">Event</a></li>
      <li class="active">{{ object.name }}</li>
    </ol>

    {% if request.user.is_authenticated %}
    <a class="btn btn-primary pull-right" href="{% url 'member:update_event_and_gallery' object.pk %}"><i class="icon-edit icon-white"></i> Update Event and Gallery</a>
     {% endif %}

    <h2>Event Detail</h2>
</div>



<div class="container-photo">
    <div class="row">


         <div class="col-xs-12">
            <p>Event Name: {{ object.name }}</p>
            <p>Event Description: {{object.description }}</p>
        </div>
            <H3>Event Gallery</H3>
        <div class="photo">
        {% for gallery in event.gallery_set.all %}

            <div>
                <p>
                    {% if gallery.image %}
                     <img src="{{ gallery.image.url}}" class="img-responsive" >
                {% endif %}
                </p>

            </div>
        {% endfor %}
    </div>
</div>
</div>

<div class="page-footer">

</div>
{% endblock  %}

member/templates/member/event_list.html
{% extends parent_template|default:"member/base_member.html" %}

{% block title %}Events{% endblock title %}

{% block body %}

<div class="page-header">
    <ol class="breadcrumb">
      <li class="active">Event</li>
    </ol>

    {% if request.user.is_authenticated %}
    <a class="btn btn-primary pull-right" href="{% url 'member:create_event_and_gallery' %}"><i class="icon-plus icon-white"></i> Add Event and Gallery</a>
     {% endif %}

    <h1>Event List</h1>
</div>

<table class="table table-striped">
    <tr>
        <th>Event</th>
    </tr>
    {% for object in object_list %}
    <tr>
        <td><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></td>
        <td>
                    <a href="{% url 'member:event-delete' object.pk %}">
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash">Delete</span>
            </button></a>
        </td>
    </tr>
    {% endfor %}



</table>

{% endblock  %}

member/templates/member/execmember_list.html
{% extends parent_template|default:"member/base_member.html" %}

{% block body %}

    <div class="page-header">
        {% if perms.member.add_exec_member %}
            <a class="btn btn-primary pull-right" href="{% url 'member:execomember-create' %}"><i class="icon-plus icon-white"></i> Add New Executive Member</a>
            {% endif %}
        <h1>Executive Members List</h1>
    </div>

    <div class="container-fluid">
        <div class="row">

    <div class="col-sm-8 col-md-9">

     {% if persons %}

    <table>
        <tr>
            <th>sl.</th>
            <th>Name and Position</th>
            <th>Photo</th>
            <th>Member Period</th>
            <th>Active</th>
            <th>Contact</th>
        </tr>
        {% for exec in members %}
        <tr>
            <td>{{forloop.counter}}.</td>
            <td>{{exec.name}}<br>
            {{exec.committee_position}}
            </td>
            <td><a href="{% url 'member:person-list'  %}">
            <img src="{{ exec.name.photo_url|default_if_none:'#'}}" class="img-responsive">
                </a></td>
            <td>
            {{exec.member_start_date }}<br>
           {{exec.member_end_date}}
            </td>
            <td>{{exec.is_active|yesno:"Active,Expired"}}</td>
                <td>{{ exec.name.email }}
                    {{ exec.name.tele_land }}
                    {{ exec.name.tele_cell }}

            </td>
        </tr>
        {% endfor %}

    </table>
    {% else %}
        <p>No member in the list.</p>
    {% endif %}
    </div>
    </div>
</div>
{% endblock %}

member/templates/member/form_template.html
{% for field in form %}

<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-4">{{field.label_tag}}
    </label>
    <div class="col-sm-8">{{ field }}</div>
</div>

{% endfor %}

member/templates/member/gallery_all.html
{% extends parent_template|default:"member/base_member.html" %}

{% block title %}Gallery{% endblock title %}

{% block body %}

<div class="page-header">
    <a class="btn btn-primary pull-right" href="{% url 'member:event-list' %}"><i class="icon-plus icon-white"></i> Go back to event list</a>
    <h1>Gallery</h1>
</div>
<div class="container-photo">
<div class="row">
<div class="photo">

         {% for object in object_list %}

            <div class="col-xs-12">

        {{object.event }}
        </div>

            <div>

                <p>
                    {% if object.image %}
                     <img src="{{ object.image.url}}" class="img-responsive" >
                {% endif %}
                </p>

            </div>

        {% endfor %}
    </div>
 </div>

</div>

</div>






{% endblock %}

member/templates/member/latest_event.html
{% block left_top_block %}


<div class="left_top_block ">


    <h4 align=center>Latest Event</h4>

    {% for gallery in gallery_list %}


            <div class="col-xs-5 left-img">

            {% if gallery.image %}
                 <img src="{{ gallery.image.url}}" height=150px; width=80% class="img-responsive">
            {% endif %}

            </div>
                <h4>{{ gallery.event.name }}</h4>
                <p>{{ gallery.event.description|truncatechars:100 }}</p>

            <div >
                <p><a class="btn btn-primary btn-xs" href="{% url 'member:event-detail' gallery.event.pk %}">See Datails &raquo;</a></p>
            </div>

    {% empty %}
       No recent event
    {% endfor %}

</div>



{% endblock %}

member/templates/member/latest_news.html
{% block right_top_block %}

<div class="right_top_block ">
    <h4 align=center>Latest News</h4>
    <ul>
        {% for news in news_list %}


        <li><h4>{{ news.title }}</h4>
            {{ news.news|truncatechars:200  }}
            <p><a class="btn btn-primary btn-xs" href="{% url 'member:news-detail' news.pk %}">See Datails &raquo;</a></p>

        </li>


        {% empty %}
           No recent news
        {% endfor %}
    </ul>
</div>



{% endblock %}

member/templates/member/membership_list.html
{% extends parent_template|default:"member/base_member.html" %}

{% block body %}

        <div class="page-header">
           <ol class="breadcrumb">
              <li class="">Membership</li>
            </ol>
            <h1>Membership Category</h1>
        </div>

    <div class="container-fluid">
        <div class="row">



        <div class="col-sm-8 col-md-9">

    {% for entry in entries %}
            <p>{{entry.category}}.</p>
     {% endfor %}

    </div>
    </div>
    </div>

{% endblock %}

member/templates/member/news_detail.html
{% extends parent_template|default:"member/base_member.html" %}

{% block body %}

<div class="container-fluid songs-container">

    <div class="row-content">
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'member:news-list' %}">View All News</a></li>
            </ul>

        </div>


        <!-- Left Album Info -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">

                    <h4>{{news.title}}</h4>
                    <p>{{news.news}}</p>
                    See Documents:
                    <a href="{% url 'member:news-detail' news.id %}">
                        {% if news.docfile %}
                            <a href="{{ news.docfile.url }}">{{ news.docfile.name}}</a>
                        {% else %}
                            <h3>No documents to display</h3>
                        {% endif %}
                    </a>
                </div>
            </div>
        </div>


        </div>
    </div>
{% endblock %}

member/templates/member/news_form.html
{% extends parent_template|default:"member/base_member.html" %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <!--{% include 'member/form_template.html' %}-->
                            <div class="form-group">
                                <div class="col-sm-offset-6 col-sm-6">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

member/templates/member/person_confirm_delete.html
{% extends parent_template|default:"member/base_member.html" %}

{% block body %}

<div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                    <h4>Do you want to delete Member: {{person.name}}?</h4>
                        <form action="" method="post">
                            {% csrf_token %}
                           <button class="btn btn-warning btn-sm">Delete</button>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


<div class="container-fluid">

        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                    <h4>Do you want to delete Member: {{person.name}}?</h4>
                        <form action="" method="post">
                            {% csrf_token %}
                           <button type="button" class="btn btn-warning btn-sm">Delete</button>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

member/templates/member/person_list.html
{% extends parent_template|default:"member/base_member.html" %}
{% load crispy_forms_tags %}

{% block body %}


    {% if perms.member.add_person %}

        <div class="page-header">
            <div class="row">
            <div class="col-sm-3 ">
                   <a class="btn btn-primary" href="{% url 'member:all-member' %}">View All Member</a>

            </div>

            <a class="btn btn-primary pull-right" href="{% url 'member:person-create' %}"><i class="icon-plus icon-white"></i> Add New Member</a>
                </div>
        </div>
    {% endif %}

    <div class="container-fluid">
        <div class="row ">

        <div style="overflow-x:auto;">

        <div class="col-sm-8 col-md-9">
            <h3>Members List</h3>

        {% if persons %}
            <table>

            <tr>
                <th>sl.</th>
                <th>Name and Position</th>
                <th>Photo</th>
                <th>Organisation & Address</th>
                <th>Contact</th>
            </tr>



            {% for person in persons %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>{{person.name}}<br>
                {{person.present_position}}</td>

                <td><a href="{% url 'member:member-detail' person.id%}">
                <img src="{{ person.photo_url|default_if_none:'#'}}" class="img-responsive">
                </a></td>

                <td>
                {{person.organization}}<br>
                {{person.address}}
                </td>

                <td>
                 {{person.tele_land}}<br>
                 {{person.tele_cell}}<br>
                 {{person.email}}
                </td>

                {% if user.pk == person.user.pk or user.is_superuser  %}
                <td>
                    <a href="{% url 'member:person-update' person.id%}">
                <button type="button" class="btn btn-primary btn-sm">
                    <span class="glyphicon glyphicon-pencil">Update</span>
                </button></a>
                </td>

                {% endif %}

                <td><a href="{% url 'member:person-delete' person.id%}">
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-trash">Delete</span>
                </button>
                </a></td>

            </tr>

            {% endfor %}
            </table>
        {% else %}
            <p>No person in the list.</p>
        {% endif %}
        </div>
            </div>
    </div>
    </div>
{% endblock %}