alumni/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from  django.conf.urls.static import static


from django.views.generic import (
    RedirectView, TemplateView)

from member import urls as member_urls
from contact import urls as contact_urls
from user import urls as user_urls


urlpatterns = [


    # url(r'^$',
    #     RedirectView.as_view(
    #         pattern_name='blog_post_list',
    #         permanent=False)),
    url(r'^about/$',
        TemplateView.as_view(
            template_name='site/about.html'),
        name='about_site'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include(member_urls)),
    url(r'^contact/', include(contact_urls)),

    url(r'^user/',
        include(
            user_urls,
            app_name='user',
            namespace='dj-auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.conf.urls import url
from . import views

from .forms import MemberForm
from django import forms

app_name = 'member'
urlpatterns = [

    url(r'^$', views.HomePageView.as_view(), name='home'),

    # Member
    url(r'^(?P<pk>[0-9]+)/$', views.MemberDetailView.as_view(), name='member-detail'),
    url(r'member/add/$', views.AlbumCreate.as_view(), name='member-add'),
    url(r'^person/$', views.GeneralMemberView.as_view(), name='person-list'),
    url(r'^lifemember/$', views.LifeMemberView.as_view(), name='lifemember-list'),
    url(r'^person/create$', views.PersonCreate.as_view(), name='person-create'),
    url(r'^person/(?P<pk>[0-9]+)/update$', views.PersonUpdate.as_view(), name='person-update'),
    url(r'^person/(?P<pk>[0-9]+)/delete$', views.PersonDelete.as_view(), name='person-delete'),
    url(r'^allmember/$', views.AllMemberListView.as_view(), name='all-member'),

    # Executive Member
    url(r'^execomember/$', views.ExeCommListView.as_view(), name='execomember-list'),
    url(r'^execomember/create$', views.ExeCommMembCreate.as_view(), name='execomember-create'),

    # Member Category
    url(r'^membercat/$', views.MembershipView.as_view(), name='member-cat'),
    url(r'^membercat/create/$', views.MemberCatCreate.as_view(), name='membercat-create'),

    # Constitution
    url(r'^cons/$', views.ConstitutionView.as_view(), name='cons-list'),
    url(r'^cons/create/$', views.ConstitutionCreate.as_view(), name='cons-create'),
    url(r'^cons/(?P<pk>[0-9]+)/update$', views.ConstitutionUpdate.as_view(), name='cons-update'),
    url(r'^cons/(?P<pk>[0-9]+)/delete$', views.ConstitutionDelete.as_view(), name='cons-delete'),

    # News
    url(r'^news/$', views.NewsListView.as_view(), name='news-list'),
    url(r'^news/create/$', views.NewsCreate.as_view(), name='news-create'),
    url(r'^news/(?P<pk>\d+)/$', views.NewsDetailView.as_view(), name='news-detail'),
    url(r'^news/(?P<pk>[0-9]+)/update/$', views.NewsUpdate.as_view(), name='news-update'),
    url(r'^news/(?P<pk>[0-9]+)/delete/$', views.NewsDelete.as_view(), name='news-delete'),


    # Event and Gallery
    url(r'^gallery/$', views.GalleryList.as_view(), name='gallery-list'),
    url(r'^gallery/(?P<pk>\d+)/$', views.GalleryDetailView.as_view(), name='gallery-detail'),
    url(r'^event/$', views.EventList.as_view(), name='event-list'),
    url(r'^event/(?P<pk>\d+)/$', views.EventDetailView.as_view(), name='event-detail'),
    url(r'^event/gallery/$', views.EventGalleryListView.as_view(), name='event-gallery'),
    url(r'^event/create/$', views.EventCreateView.as_view(), name='create_event_and_gallery'),
    url(r'^event/(?P<pk>\d+)/update/$', views.EventUpdateView.as_view(), name='update_event_and_gallery'),
    url(r'^event/(?P<pk>[0-9]+)/delete/$', views.EventDelete.as_view(), name='event-delete'),
    url(r'^gallery/all/$', views.GalleryAllList.as_view(), name='gallery-all'),

    # Search

    url(r'^search/$', views.SearchListView.as_view(), name='search'),
   ]

user/urls.py
from django.conf.urls import include, url
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    RedirectView, TemplateView)

from .views import (
    ActivateAccount, CreateAccount,
    DisableAccount, ProfileDetail, ProfileUpdate,
    PublicProfileDetail, ResendActivationEmail)

password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'user/password_change_form.html',
         'post_change_redirect': reverse_lazy(
            'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'user/password_reset_form.html',
         'email_template_name':
            'user/password_reset_email.txt',
         'subject_template_name':
            'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'user/password_reset_complete.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'user/user_create_done.html')),
        name='create_done'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'^login/$',
        auth_views.login,
        {'template_name': 'user/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name': 'user/logged_out.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='logout'),
    url(r'^password/', include(password_urls)),
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),
    url(r'^profile/edit/$',
        ProfileUpdate.as_view(),
        name='profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}


{% load member_template_tags %}

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 {% block title_tag %}<title>{% block title %}{% if page.title %}{{ page.title }}{% endif %}{% endblock %}</title>{% endblock %}

    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link href="{% static 'site/css/jquery-ui.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link href="{% static 'site/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/bootstrap-social.css' %}" rel="stylesheet">
    <link href="{% static 'site/css/mystyle.css' %}" rel="stylesheet">


    <!--<link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet">-->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">-->
    <!--<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>-->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">-->
    <!--<link href="{% static './css/bootstrap-social.css' %}" rel="stylesheet">-->
    <!--<link href="{% static './css/mystyle.css' %}" rel="stylesheet">-->




      {% block head_extra %}

        {% endblock head_extra %}


  </head>

  <body>

    {% include 'navbar.html' %}

    {% if messages %}
        <div class="row">
          <div class="twelve columns">
            <ul class="messages">
              {% for message in messages %}
                {% if message.tags %}
                  <li class="{{ message.tags }}">
                {% else %}
                  <li>
                {% endif %}
                {{ message }}</li>
              {% endfor %}
        </ul></div></div>
      {% endif %}

    <div class="container">
    <div class="row">
                <!--/span-->



            <div class="col-sm-3 col-md-2 sidebar">
            {% block sidebar_block %}
                {% entry_history %}
                {% endblock %}
            </div>

            <div class="col-sm-9 offset-sm-3 col-md-10 offset-sm-2 main">
             {% block body %}{% endblock %}
                <div class="content"><br><br><br><br><br></div>

            </div>

      </div>
    </div>
        <div class="container-fluid">
        <div class="row">
            <div class="content"><br><br><br><br><br></div>
            </div>
    </div>



   <footer class="row-footer">
        <div class="container-fluid">
            <div class="row">
                            <div class="col-xs-12">
                <div class="col-xs-5 col-xs-offset-1 col-sm-2 col-sm-offset-1">
                    <h5>Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'member:home' %}">Home</a></li>
                        <li><a href="{% url 'about_site' %}">About</a></li>
                        <li><a href="{% url 'member:event-gallery' %}">Gallery</a></li>
                        <li><a href="{% url 'contact' %}">Contact</a></li>
                    </ul>
                </div>
                <div class="col-xs-6 col-sm-5">
                    <h5>Our Address</h5>
                    <address>
		              APCE, Carzon Hall<br>
		              Dhaka, Bangladesh<br>
		              <i class="fa fa-phone" id="telephone"></i>: +8802 1234 5678<br>
		              <i class="fa fa-fax"></i>: +8802 8765 4321<br>
		              <i class="fa fa-envelope"></i>: <a href="mailto:masudpol@gmail.com">apce-alumni</a>
		           </address>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="nav navbar-nav" style="padding: 40px 10px;">
                        <a class="btn btn-social-icon btn-google-plus" href="http://google.com/+"><i class="fa fa-google-plus"></i></a>
                        <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i class="fa fa-facebook"></i></a>
                        <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i class="fa fa-linkedin"></i></a>
                        <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i class="fa fa-twitter"></i></a>
                        <a class="btn btn-social-icon btn-youtube" href="http://youtube.com/"><i class="fa fa-youtube"></i></a>
                        <a class="btn btn-social-icon" href="mailto:masudpol@gmail.com"><i class="fa fa-envelope-o"></i></a>
                    </div>
                </div>
                <!--<div class="col-xs-12">-->
                    <!--<p style="padding:10px;"></p>-->

                <!--</div>-->

            </div></div>
            <p align=center>Design & Developed by: Md. Ohiduzzaman, © Copyright 2016 Applied Chemistry and Chemical Engineering Department Alumni</p>
        </div>

    </footer>

        {% block bottom_script %}
        <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
        <script src="{% static 'site/js/jquery-1.12.4.js' %}"></script>
        <script src="{% static 'site/js/jquery-ui.js' %}"></script>
        <script src="{% static 'site/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'site/js/photo.js' %}"></script>

        <!--<script src="https://code.jquery.com/jquery-1.12.4.js"></script>-->
        <!--<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>-->
        <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->



         <script type="text/html" id="gallery-template">
            <div id="gallery-__prefix__">
                {{ formset.empty_form }}
            </div>
        </script>

        <!-- Le javascript
        ================================================== -->

    {% endblock bottom_script %}


  </body>
</html>

templates/navbar.html
{% load staticfiles %}
{% load nav %}



<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" >
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'member:home' %}"><img src="{% static 'site/images/index.png' %}" class="img-responsive"  alt="logo"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="{% active_page request 'home' %}">
                        <a href="{% url 'member:home' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="{% active_page request 'about'  %}">
                        <a href="{% url 'about_site' %}">
                            <span class="glyphicon glyphicon-info-sign" aria-hidden="false"></span> About
                        </a>
                    </li>

                    {% url 'member:person-list' as url_person %}
                    {% url 'member:execomember-list' as url_exemember %}
                    {% url 'member:lifemember-list' as url_lifemember %}
                    {% url 'member:cons-list' as url_cons %}
                    <li class="dropdown {% if request.path == url_person or request.path == url_exemember or request.path == url_cons  %}active{% endif %}">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>Alumni
                            <span class="caret"></span>
                        </a>


                      <ul class="dropdown-menu">
                          <li class="">
                                <a href="{{url_person}}">
                                    <span class="" aria-hidden="true"></span>Member</a></li>

                         <li class="">
                                <a href="{{url_exemember}}">
                                    <span class="" aria-hidden="true"></span>Execuitve Member</a></li>
                          <li><a href={{url_lifemember}}>
                              <span class="" aria-hidden="true"></span>Life Member</a></li>

                        <li role="separator" class="divider"></li>
                        <li><a href="{{url_cons}}">
                            <span class="" aria-hidden="true"></span>Alumnai Constitution link</a></li>

                      </ul>
                    </li>
                    <li class="{% active_page request 'contact'  %}">
                        <a href="{% url 'contact' %}">
                            <i class="fa fa-envelope" aria-hidden="true"></i> Contact
                        </a>
                    </li>
                  </ul>



          <ul class="nav navbar-nav navbar-right">


              {% url 'member:event-list' as url_event %}
              {% url 'member:gallery-list' as url_gallery %}
              {% url 'member:news-list' as url_news %}
              {% url 'member:event-gallery' as url_event_gallery %}
              <li class="dropdown {% if request.path == url_event or request.path == url_gallery or request.path == url_news or request.path == url_event_gallery %}active{% endif %}">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>Gallery
                            <span class="caret"></span>
                        </a>


                      <ul class="dropdown-menu">
                          <li class="">
                                <a href="{{url_event}}">
                                    <span class="" aria-hidden="true"></span>&nbsp;Event List</a></li>

                         <li class="">
                                <a href="{{url_gallery}}">
                                    <span class="" aria-hidden="true"></span>&nbsp;Gallery List</a></li>
                          <li class="">
                                <a href="{{url_news}}">
                                    <span class="" aria-hidden="true"></span>&nbsp;News List</a></li>

                        <li role="separator" class="divider"></li>
                        <li><a href="{{url_event_gallery}}">
                            <span class="" aria-hidden="true"></span>&nbsp;Photo Gallery link</a></li>

                      </ul>
                    </li>



              {% if request.user.is_authenticated %}
              <li class="{% active_page request 'profile' %}">
                  <a href="{% url 'dj-auth:profile' %}">
                View Profile</a></li>

                <li class="{% active_page request 'logout' %}">
                    <a href="{% url 'dj-auth:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout</a></li>
                {% else %}
                <li class="{% active_page request 'create' %}">
                    <a href="{% url 'dj-auth:create' %}">
                Register</a></li>

                <li class="{% active_page request 'login' %}" >
                    <a href="{% url 'dj-auth:login' %}"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Log-in</a></li>
                {% endif %}




            </ul>


            </div><!-- /.navbar-collapse -->

          <!-- /.container-fluid -->
            </div>
        </nav>

    <header id="header">
    <div class="top-bar">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-8">
                    <div class="banner">
                        <h4>Dhaka University Applied Chemistry and Chemical Engineering<br> Alumni Association</h4>
                        </div>
                </div>
                 <div class="col-sm-4 col-md-4">
                <div class="search">
                    <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'member:search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search Event & Gallery" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
                </div>
                     </div>

            </div>
        </div><!--/.container-->
    </div><!--/.top-bar-->

</header>